// Generates the stand-in site icons (Requirements 20.4, 20.5):
//
//   app/icon.svg        64x64 viewBox, transparent background -> <link rel="icon">
//   app/apple-icon.png  180x180, sand-50 background          -> <link rel="apple-touch-icon">
//
// Both are Next.js file-convention metadata (docs/NEXT16_NOTES.md item 2):
// their mere presence in app/ emits the <link> tags, no code references them.
//
// The mark is an oval dashed-stroke stamp with a monoline "RS" in the centre,
// drawn in `tokens.ink` so it follows app/globals.css. Letters are paths, not
// <text>, so the PNG rasterises identically on any machine (sharp's SVG
// renderer needs system fonts for <text>).
//
// FILE-REPLACEMENT SWAP: these are placeholders. The designer delivers the
// final mark by dropping files at exactly `app/icon.svg` and
// `app/apple-icon.png` (same names, same sizes) — nothing else changes. This
// script is NOT wired into any npm script; run it once by hand
// (`npx tsx scripts/make-icons.ts`) and commit the output. Do not re-run it
// after the designer's files land, or they will be overwritten.

import { writeFileSync } from "node:fs";
import path from "node:path";
import sharp from "sharp";
import { tokens } from "../lib/tokens";

const ROOT = process.cwd();
const ICON_SVG = path.join(ROOT, "app", "icon.svg");
const APPLE_PNG = path.join(ROOT, "app", "apple-icon.png");
const APPLE_SIZE = 180;

/**
 * The stamp mark in a 64x64 coordinate system.
 *
 * - outer ellipse: dashed "perforated" edge
 * - inner ellipse: thin solid border, as on the Stamp motif
 * - "R" and "S": monoline strokes, ~14 units tall, centred
 */
function stampMark(background: string | null, size: number | null): string {
  const ink = tokens.ink;
  const dims = size === null ? "" : ` width="${size}" height="${size}"`;
  const bg = background === null ? "" : `\n  <rect width="64" height="64" fill="${background}"/>`;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"${dims} role="img" aria-label="Returning Sands">${bg}
  <ellipse cx="32" cy="32" rx="28" ry="20" fill="none" stroke="${ink}" stroke-width="2.5" stroke-dasharray="4 3" stroke-linecap="round"/>
  <ellipse cx="32" cy="32" rx="24" ry="16" fill="none" stroke="${ink}" stroke-width="1"/>
  <g fill="none" stroke="${ink}" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round">
    <path d="M22.5 39 V25 H27 A3.5 3.5 0 0 1 27 32 H22.5 M26.5 32 L30.5 39"/>
    <path d="M41 26.5 C38 24.5 34 25 34 28.5 C34 32 41 32 41 35.5 C41 39 37 39.5 33.5 37.5"/>
  </g>
</svg>
`;
}

async function main(): Promise<void> {
  // icon.svg: the SVG itself, transparent, scalable.
  const iconSvg = `<!-- generated by scripts/make-icons.ts; replace with the designer's final mark -->\n${stampMark(null, null)}`;
  writeFileSync(ICON_SVG, iconSvg);
  console.log(`wrote ${path.relative(ROOT, ICON_SVG)} (${Buffer.byteLength(iconSvg)} bytes)`);

  // apple-icon.png: iOS ignores transparency, so paint the sand-50 paper.
  const appleSvg = stampMark(tokens["sand-50"], APPLE_SIZE);
  const png = await sharp(Buffer.from(appleSvg)).resize(APPLE_SIZE, APPLE_SIZE).png().toBuffer();
  writeFileSync(APPLE_PNG, png);
  const meta = await sharp(png).metadata();
  console.log(
    `wrote ${path.relative(ROOT, APPLE_PNG)} (${meta.width}x${meta.height}, ${png.byteLength} bytes)`,
  );
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
